DROP FUNCTION IF EXISTS roaring32_create ;
DROP FUNCTION IF EXISTS roaring32_remove ;
DROP FUNCTION IF EXISTS roaring32_insert ;
DROP FUNCTION IF EXISTS roaring32_contains ;
DROP FUNCTION IF EXISTS roaring32_count ;
DROP FUNCTION IF EXISTS roaring32_json ;
DROP FUNCTION IF EXISTS roaring32_and ;
DROP FUNCTION IF EXISTS roaring32_or ;
DROP FUNCTION IF EXISTS roaring32_xor ;
DROP FUNCTION IF EXISTS roaring32_and_count ;
DROP FUNCTION IF EXISTS roaring32_or_count ;
DROP FUNCTION IF EXISTS roaring32_xor_count ;
DROP FUNCTION IF EXISTS roaring32_group_create ;
DROP FUNCTION IF EXISTS roaring32_group_and ;
DROP FUNCTION IF EXISTS roaring32_group_or ;
DROP FUNCTION IF EXISTS roaring32_group_xor ;
DROP FUNCTION IF EXISTS roaring32_group_and_count ;
DROP FUNCTION IF EXISTS roaring32_group_or_count ;
DROP FUNCTION IF EXISTS roaring32_group_xor_count ;
CREATE FUNCTION IF NOT EXISTS roaring32_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_remove RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_insert RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_contains RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_json RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_group_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
DROP FUNCTION IF EXISTS roaring64_create ;
DROP FUNCTION IF EXISTS roaring64_remove ;
DROP FUNCTION IF EXISTS roaring64_insert ;
DROP FUNCTION IF EXISTS roaring64_contains ;
DROP FUNCTION IF EXISTS roaring64_count ;
DROP FUNCTION IF EXISTS roaring64_json ;
DROP FUNCTION IF EXISTS roaring64_and ;
DROP FUNCTION IF EXISTS roaring64_or ;
DROP FUNCTION IF EXISTS roaring64_xor ;
DROP FUNCTION IF EXISTS roaring64_and_count ;
DROP FUNCTION IF EXISTS roaring64_or_count ;
DROP FUNCTION IF EXISTS roaring64_xor_count ;
DROP FUNCTION IF EXISTS roaring64_group_create ;
DROP FUNCTION IF EXISTS roaring64_group_and ;
DROP FUNCTION IF EXISTS roaring64_group_or ;
DROP FUNCTION IF EXISTS roaring64_group_xor ;
DROP FUNCTION IF EXISTS roaring64_group_and_count ;
DROP FUNCTION IF EXISTS roaring64_group_or_count ;
DROP FUNCTION IF EXISTS roaring64_group_xor_count ;
CREATE FUNCTION IF NOT EXISTS roaring64_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_remove RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_insert RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_contains RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_json RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_group_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
DROP FUNCTION IF EXISTS roaring32_nullsafe_create ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_remove ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_insert ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_contains ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_json ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_and ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_or ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_xor ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_and_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_or_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_xor_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_create ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_and ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_or ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_xor ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_and_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_or_count ;
DROP FUNCTION IF EXISTS roaring32_nullsafe_group_xor_count ;
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_remove RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_insert RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_contains RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_json RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring32_nullsafe_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring32_nullsafe_group_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
DROP FUNCTION IF EXISTS roaring64_nullsafe_create ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_remove ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_insert ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_contains ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_json ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_and ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_or ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_xor ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_and_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_or_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_xor_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_create ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_and ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_or ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_xor ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_and_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_or_count ;
DROP FUNCTION IF EXISTS roaring64_nullsafe_group_xor_count ;
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_remove RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_insert RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_contains RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_json RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE FUNCTION IF NOT EXISTS roaring64_nullsafe_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_create RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_and RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_or RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_xor RETURNS STRING SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_and_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_or_count RETURNS INTEGER SONAME 'libmysql_roaring.so';
CREATE AGGREGATE FUNCTION IF NOT EXISTS roaring64_nullsafe_group_xor_count RETURNS INTEGER SONAME 'libmysql_roaring.so';